from .life_seal import LIFE_SEAL_INTERPRETATIONS
from .soul_number import SOUL_NUMBER_INTERPRETATIONS
from .personality_number import PERSONALITY_NUMBER_INTERPRETATIONS
 

__all__ = ["LIFE_SEAL_INTERPRETATIONS", "SOUL_NUMBER_INTERPRETATIONS", "PERSONALITY_NUMBER_INTERPRETATIONS"]